id: password-protection
displayName: "Password Protection for Active Directory"
components:
  - id: "service"
    name: "Service"
    displayName: "Password Protection service"
    artifacts:
      - id: "service-win-x64"
        name: "x64"
        displayName: "Windows (x64)"
