#
# Module manifest for module 'LithnetPasswordProtection'
#
# Generated by: Ryan Newington
#
# Generated on: 28/08/2015
#

@{

# Version number of this module.
ModuleVersion = '1.0.0.0'

# ID used to uniquely identify this module
GUID = 'e6a12c2f-7a92-44af-9ec8-6473d479cf27'

# Author of this module
Author = 'Lithnet Pty Ltd'

# Company or vendor of this module
CompanyName = 'Lithnet Pty Ltd'

# Copyright statement for this module
Copyright = 'Copyright 2023 Lithnet Pty Ltd'

# Description of the functionality provided by this module
Description = 'PowerShell module for Lithnet Password Protection for Active Directory'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.0'

# Name of the Windows PowerShell host required by this module
PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64, IA64) required by this module
ProcessorArchitecture = 'Amd64'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
#FormatsToProcess = @("ManagementAgent.format.ps1xml", "Attribute.format.ps1xml")

# Modules to import as nested modules of the module specified in ModuleToProcess
RootModule = 'LithnetPasswordProtection.dll'

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
#ModuleList = @()

# List of all files packaged with this module
FileList = @()

# Private data to pass to the module specified in ModuleToProcess
PrivateData = ''

}